### ISSUE TITLE
Published?

### ISSUE THREAD

**Issue by whenceforth** [cashapp/jooq-encryption#13]
Hi, 
I'd like to try this project out but it does not seem to have been published. Am I looking in the wrong places? Or have you not published it? Any plan to publish? 

Thanks!

**Comment by yoavamit** [comment]
Seems like it wasn't published to Maven Central for some reason, but you can play around with this library by downloading the jar file from [here](https://github.com/cashapp/jooq-encryption/releases/tag/v1.0.0) in the meantime.

I'll make sure it's properly published to Maven as well.
Thanks!

**Comment by yoavamit** [comment]
After taking a closer look I discovered the Gradle configuration for publishing the jar to Maven Central didn't really work.
I'm going to fix it in PR #15 and will try republishing it there soon.

**Comment by yoavamit** [comment]
This is finally fixed, you can find this library in Maven Central now here https://central.sonatype.com/namespace/app.cash.jooq
