### ISSUE TITLE
support jOOQ 3.18.17

### ISSUE THREAD

**Issue by dbist** [cashapp/jooq-encryption#20]
I noticed the current release is built with version 3.17.6. The dialect I'm using requires professional edition and the one I am using is only available in the latest jar. jOOQ does not publish older non-OSS jars. Any chance you can update the current library to the latest jOOQ?
https://github.com/cashapp/jooq-encryption/blob/main/build.gradle.kts#L18C15-L22

**Comment by yoavamit** [comment]
@dbist sorry this took so long to fix, I had the branch ready and I forgot to push it 😅 

This should be resolved now - I created a new release, [v1.0.2](https://github.com/cashapp/jooq-encryption/tree/v1.0.2) that has the latest jooq release as a dependency.
